### ISSUE TITLE
Could not find a declaration file for module 'svelte'. 

### ISSUE THREAD

**Issue by CAJazzer** [pyoner/svelte-ts-template#1]
Template includes svelte.d.ts but references to svelte in imports does not find type declaration file (maybe tsconfig.json config?)  Tried doing the following and got the error:
```
import { onMount } from 'svelte';
```
npm run build error is:
```
error TS7016: Could not find a declaration file for module 'svelte'.
```

**Comment by pyoner** [comment]
@CAJazzer thank you for the issue, fixed
Please check it!

**Comment by CAJazzer** [comment]
Verified.  Thank you!
