### ISSUE TITLE
Build an empty project does not work

### ISSUE THREAD

**Issue by Alexey-Sch** [pyoner/svelte-ts-template#3]
I do everything in steps, as described in readme file. When I run ```npm run dev```, build fails with next output:

![image](https://user-images.githubusercontent.com/31435630/57227297-b5e9c300-7019-11e9-84ab-1c81ca803489.png)

I do not have a globally installed TypeScript, it runs from the ```node_modules``` directory of project from latest commit of ```master``` branch.

**Comment by pyoner** [comment]
I can not reproduce the error
Could you provide me `package-lock.json` and node version?

**Comment by Alexey-Sch** [comment]
```
> node -v
v11.12.00
Windows 8.1
```


[package-lock.json.txt](https://github.com/pyoner/svelte-ts-template/files/3151500/package-lock.json.txt)

**Comment by aimuzov** [comment]
i can’t reproduce this bug.

```
node v12.1.0
npm v6.9.0
macos v10.14.4
```

**Comment by pyoner** [comment]
Fixed

**Comment by jesmasa** [comment]
There's a problem in createProxyHost function.
- when using 'file' input parameter name property (file.name) '\\' directoty separator is used
- when using 'fileName' in all returned proxy functions '/' directory separator is used
so file name comparisons inside proxy functions don't work as expected.
