### ISSUE TITLE
UMD and IIFE output formats are not supported for code-splitting builds.

### ISSUE THREAD

**Issue by Florian007** [pyoner/svelte-ts-template#4]
Hi, everthing works great except dynamic imports. For example trying to load a component with 
```

<script>
  import { onMount } from "svelte";
  let Component;
  onMount(async () => {
    const module = await import("./components/Test.svelte");
    Component = module.default;
  });
</script>

<svelte:component this={Component} />
```

results in the error: 
UMD and IIFE output formats are not supported for code-splitting builds.

And if setting the output.format to "esm" in rollup.config.js ends in loading and displaying nothing.

Thank you for watching!

**Comment by PaulMaly** [comment]
@Florian007 Actually, this issue not related to the current repo. This related to Rollup. So, you really not able to use UMD and IIFE with code-splitting. I think you should use ESM and provide the way to load dynamic chunks with something like SystemJS. More info: https://github.com/rollup/rollup/issues/2072

**Comment by pyoner** [comment]
Hi, @Florian007 
You example is not typescript code, because you missed the attribute `lang="ts"`
Yes, your issue is not related to this repo
